INSERT INTO tbl_cards (hp, name, informacoes, attack, damage, weak, ressis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '30', 'Electric', NULL, '1 Colorless', 57, 1, 7, 1),
(80, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Electric', NULL, '1 Colorless', 22, 1, 7, 2),
(120, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '80', 'Electric', NULL, '2 Colorless', 8, 1, 7, 3),
(50, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', NULL, '1 Colorless', 43, 1, 5, 1),
(60, 'Kadabra', 'Psi Pokémon', 'Recover', '30', 'Psychic', NULL, '1 Colorless', 32, 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', NULL, '3 Colorless', 1, 1, 5, 3),
(70, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', NULL, '1 Colorless', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', NULL, '2 Colorless', 26, 1, 6, 2),
(100, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', NULL, '3 Colorless', 8, 1, 6, 3),
(60, 'Oddish', 'Weed Pokémon', 'Absorb', '20', 'Fire', NULL, '1 Colorless', 58, 2, 3, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '30', 'Fire', NULL, '2 Colorless', 32, 2, 3, 2),
(90, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', NULL, '2 Colorless', 15, 2, 3, 3),
(60, 'Eevee', 'Evolution Pokémon', 'Tackle', '20', 'Fighting', NULL, '1 Colorless', 51, 2, 7, 1),
(70, 'Flareon', 'Flame Pokémon', 'Flamethrower', '60', 'Water', NULL, '2 Colorless', 12, 2, 1, 2),
(70, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', NULL, '1 Colorless', 4, 2, 4, 2),
(70, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Electric', NULL, '2 Colorless', 28, 2, 2, 2),
(60, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', NULL, '1 Colorless', 56, 2, 7, 1),
(80, 'Persian', 'Classy Cat Pokémon', 'Slash', '30', 'Fighting', NULL, '1 Colorless', 17, 2, 7, 2),
(70, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Psychic', NULL, '1 Colorless', 57, 3, 3, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', NULL, '1 Colorless', 25, 3, 3, 2),
(100, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', NULL, '2 Colorless', 13, 3, 3, 2),
(60, 'Grimer', 'Sludge Pokémon', 'Poison Gas', '10', 'Psychic', NULL, '1 Colorless', 48, 3, 3, 1),
(70, 'Omanyte', 'Spiral Pokémon', 'Water Gun', '10+', 'Grass', NULL, '1 Colorless', 52, 3, 2, 1),
(80, 'Omastar', 'Spiral Pokémon', 'Hydro Pump', '30+', 'Grass', NULL, '2 Colorless', 26, 3, 2, 2),
(90, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '20', 'Grass', NULL, '1 Colorless', 50, 3, 2, 1),
(100, 'Kabutops', 'Shellfish Pokémon', 'Slash', '40', 'Grass', NULL, '2 Colorless', 24, 3, 2, 2),
(60, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Psychic', NULL, '1 Colorless', 55, 3, 2, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', '20', 'Psychic', NULL, '2 Colorless', 28, 3, 2, 2),
(70, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', NULL, '1 Colorless', 53, 3, 4, 1),
(90, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', NULL, '2 Colorless', 11, 3, 4, 2);
