INSERT INTO tbl_cards (hp, name, informacoes, attack, damage, weak, ressis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', NULL, '1 Colorless', 61, 1, 7, 1),
(70, 'Raticate', 'Mouse Pokémon', 'Super Fang', '40', 'Fighting', NULL, '1 Colorless', 20, 1, 7, 2),
(50, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '10', 'Psychic', NULL, '1 Colorless', 32, 1, 3, 1),
(70, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', NULL, '2 Colorless', 36, 1, 3, 2),
(90, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', NULL, '3 Colorless', 7, 1, 3, 3),
(50, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Hazard', '30', 'Psychic', NULL, '1 Colorless', 54, 1, 3, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', NULL, '2 Colorless', 36, 1, 3, 2),
(100, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', NULL, '3 Colorless', 11, 1, 3, 3),
(60, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Electric', NULL, '1 Colorless', 59, 1, 2, 1),
(70, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '20', 'Electric', NULL, '1 Colorless', 36, 1, 2, 2),
(90, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Electric', NULL, '3 Colorless', 13, 1, 2, 3),
(60, 'Venonat', 'Insect Pokémon', 'Stun Spore', '10', 'Fire', NULL, '1 Colorless', 63, 2, 3, 1),
(70, 'Venomoth', 'Poison Moth Pokémon', 'Venom Powder', '10', 'Fire', NULL, '1 Colorless', 29, 2, 3, 2),
(80, 'Pinsir', 'Stag Beetle Pokémon', 'Guillotine', '50', 'Fire', NULL, '2 Colorless', 9, 2, 3, 1),
(70, 'Tauros', 'Wild Bull Pokémon', 'Stomp', '20+', 'Fighting', NULL, '2 Colorless', 21, 2, 7, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Electric', NULL, '1 Colorless', 19, 2, 7, 2),
(60, 'Exeggcute', 'Egg Pokémon', 'Hypnosis', '10', 'Fire', NULL, '1 Colorless', 52, 2, 3, 1),
(80, 'Exeggutor', 'Coconut Pokémon', 'Stomp', '20+', 'Fire', NULL, '2 Colorless', 35, 2, 3, 2),
(70, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Electric', NULL, '1 Colorless', 22, 2, 2, 2),
(100, 'Seaking', 'Goldfish Pokémon', 'Horn Attack', '30', 'Electric', NULL, '2 Colorless', 23, 2, 2, 2),
(60, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', NULL, '1 Colorless', 50, 2, 2, 1),
(70, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '20', 'Electric', NULL, '1 Colorless', 55, 3, 2, 1),
(80, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '50', 'Electric', NULL, '2 Colorless', 34, 3, 2, 2),
(60, 'Seel', 'Sea Lion Pokémon', 'Headbutt', '10', 'Electric', NULL, '1 Colorless', 58, 3, 2, 1),
(80, 'Dewgong', 'Sea Lion Pokémon', 'Aurora Beam', '50', 'Electric', NULL, '2 Colorless', 26, 3, 2, 2),
(70, 'Slowpoke', 'Dopey Pokémon', 'Headbutt', '20', 'Psychic', NULL, '1 Colorless', 55, 3, 5, 1),
(90, 'Slowbro', 'Hermit Crab Pokémon', 'Amnesia', '20', 'Psychic', NULL, '2 Colorless', 32, 3, 5, 2),
(100, 'Articuno', 'Freeze Pokémon', 'Blizzard', '50', 'Electric', NULL, '2 Colorless', 2, 3, 2, 2),
(100, 'Zapdos', 'Electric Pokémon', 'Thunderstorm', '60', 'Fighting', NULL, '3 Colorless', 15, 3, 4, 2),
(100, 'Moltres', 'Flame Pokémon', 'Fire Blast', '70', 'Water', NULL, '3 Colorless', 12, 3, 1, 2);
